name: Cypress QA Pipeline

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Executar lint
        run: yarn lint

      - name: Executar testes unitários
        run: yarn test:unit:ci

      - name: Iniciar aplicação
        run: yarn start:ci &
        
      - name: Aguardar aplicação iniciar
        run: npx wait-on http://localhost:3000

      - name: Executar testes Cypress
        run: yarn cypress run --spec "cypress/tests/ui/auth.spec.ts"

      - name: Upload de screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload de vídeos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos